import Head from 'next/head'
import Link from 'next/link';

const somewhatRandomValues = Math.random().toString(36).substring(2, 14);

export default function Home() {
    return (
        <div className="flex flex-col items-center">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <h1 className="text-center font-bold text-2xl">Thanks for visiting my project. Click to generate a valid
                    NFT QR code that
                    we could give a customer!</h1>
            </div>
            <Link href={'/qr/' + somewhatRandomValues}>
                <div
                    className="bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 mt-4 rounded-full">

                    Generate QR

                </div>
            </Link>
        </div>

    )
}
