import Head from 'next/head'
import Link from 'next/link';
import {ethers} from 'ethers';
import {HARDHAT_PRIVATE_KEY} from '/config';
import {nftContractAddress} from '/config';
import CrepesAndWaffles from "../artifacts/contracts/CrepesAndWaffles.sol/CrepesAndWaffles.json";

const somewhatRandomValues = Math.random().toString(36).substring(2, 14);

async function registerKey() {
    const key = ethers.utils.formatBytes32String(somewhatRandomValues);
    console.log(key);
    const wallet = new ethers.Wallet(HARDHAT_PRIVATE_KEY);
    console.log(wallet);
    const provider = new ethers.providers.JsonRpcProvider();
    const signer = await provider.getSigner(wallet.address);
    console.log(signer);
    const crepesAndWafflesContract = new ethers.Contract(nftContractAddress, CrepesAndWaffles.abi, signer);
    const response = await crepesAndWafflesContract.generatePermission(key);
    console.log(response);
    console.log('done');
}

export default function Home() {
    return (
        <div className="flex flex-col items-center">
            <Head>
                <title>QR Culture</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1 className="text-center font-black text-3xl">Thanks for visiting my project! </h1>
            <h1 className="text-center font-bold text-2xl pt-4"> Click to generate a valid
                    NFT QR code that
                    we could give a customer!</h1>
            <Link href={'/qr/' + somewhatRandomValues}>
                <div
                    className="bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 mt-4 rounded-full" onClick={() => registerKey()}>

                    Generate QR

                </div>
            </Link>
        </div>

    )
}
